name: nukmans-tech-landing-page
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: chuki2/nukmans-tech-landing-page
  name: nukmans-tech-landing-page
